server:
  port: 8080
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  h2:
    console:
      enabled: true
  datasource:
    url: 'jdbc:h2:mem:mydb'
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
springdoc:
  api-docs:
    path: /public/api-docs
  swagger-ui:
    path: /public/swagger-ui-custom.html
expresion-regular:
  email: ^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$
  password: ^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,16}$
jwt:
  secret-key: TExBVkVfTVVZX1NFQ1JFVEE=
  token-validity : 28800000      