server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: 'jdbc:h2:~/testdb;DB_CLOSE_ON_EXIT=FALSE'
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
springdoc:
  api-docs:
    path: /public/api-docs
  swagger-ui:
    path: /public/swagger-ui-custom.html
expresion-regular:
  email: ^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$
  password: ^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,16}$
    